project:
  type: website

website:
  title: "Reginaldo Esteves - Algoritmos"
  description: "Trabalho Individual de Algoritmos"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - text: Atividades
        menu:
          - href: posts/atividade1/index.qmd
            text: Atividade 1 – Cotação do Dólar
          - href: posts/atividade2/index.qmd
            text: Atividade 2 – Monitoramento de Frota
          - href: posts/atividade3/index.qmd
            text: Atividade 3 – Regressão Linear

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
